Hacked sysupgrade to disable hardware watchdog before upgrade

diff --git a/package/base-files/files/sbin/sysupgrade b/package/base-files/files/sbin/sysupgrade
--- a/package/base-files/files/sbin/sysupgrade
+++ b/package/base-files/files/sbin/sysupgrade
@@ -219,6 +219,15 @@ if [ ! -f /tmp/failsafe ] ; then
 	kill_remaining KILL
 fi
 
+echo "Disabling hardware watchdog"
+echo V >/dev/watchdog
+if [ $? != 0 ]; then
+ echo
+ echo "Failed to disable watchdog so refusing to upgrade. Rebooting."
+ reboot
+ exit 0
+fi
+
 if [ -n "$(rootfs_type)" ]; then
 	v "Switching to ramdisk..."
 	run_ramfs '. /lib/functions.sh; include /lib/upgrade; do_upgrade'
